### ISSUE TITLE
Update 404.html page

### ISSUE THREAD

**Issue by vkmrishad** [vkmrishad/vkmrishad.github.io#13]
Currently, the 404.html page is blank.
Help to create a unique design.

**Comment by ramyamahi** [comment]
Can you please assign this to me @vkmrishad

**Comment by vkmrishad** [comment]
@ramyamahi Make sure, it will not break other pages.
Thank you

**Comment by vkmrishad** [comment]
@ramyamahi Please PR to dev branch

**Comment by ramyamahi** [comment]
Can I add styles in the style.css file? @vkmrishad

**Comment by vkmrishad** [comment]
@ramyamahi Sure, don't spend too much time.
If you get interested free open templates, you can use that too.

**Comment by ramyamahi** [comment]
@vkmrishad  Please check the PR #15

**Comment by vkmrishad** [comment]
@ramyamahi Thank you for your contribution.
